### ISSUE TITLE
Autostart

### ISSUE THREAD

**Issue by Yotie2000** [GamerClassN7/HA_Desktop_Companion#86]
### Describe the Bug

Even with the task scheduler and moving the file into the autostart folder i can't get it to automatically start when I boot my laptop or Pc.

### Steps to Reproduce

Create a task with the task scheduler or move the file into the autostart folder

### Expected Behaviour

Automatically start when system starts.

### Version

1.0.0.4

**Comment by GamerClassN7** [comment]
since you raised many issues i suggest to conect to discord so i cna provide better help: [https://discord.com/invite/XJpT3UQ](https://discord.com/invite/XJpT3UQ)

Also i am not shure why you mention the task Scheduler you don need to do any other than fil in URL, TOken and click connect app will automatically attach it self to start up flow of windovs as described in this function [Autostart Function](https://github.com/GamerClassN7/HA_Desktop_Companion/blob/master/HADC_REBORN/Class/Helpers/Autostart.cs#L23C75-L23C124)

* not you should not move the application afterwards :)

I hope it help if you join Discord feel freee to mention me in coresponding #🏠-ha-desktop-companion chanell my Discord handler is @jonatanrek

**Comment by GamerClassN7** [comment]
CLosing due to lack of response :/

**Comment by Yotie2000** [comment]
Im sorry, i was very busy studying and totally forgot about it. Later this week i would have time to join your discord. I would love to get the autostart to work. I can see it inside the autostart menu inside the taskmanager but it just wont start when i boot my laptop..

**Comment by GamerClassN7** [comment]
> Im sorry, i was very busy studying and totally forgot about it. Later this week i would have time to join your discord. I would love to get the autostart to work. I can see it inside the autostart menu inside the taskmanager but it just wont start when i boot my laptop..

Hi, then you need to submit the log file at least :/
