### ISSUE TITLE
Entities not unavailable when turned off

### ISSUE THREAD

**Issue by Yotie2000** [GamerClassN7/HA_Desktop_Companion#88]
### Describe the Bug

The sensors in HA stay on the last value when i turn off my device instead of becoming unavailable.

### Steps to Reproduce

Turn off the device and check HA.

### Expected Behaviour

All sensors should become unavailable.

### Version

1.0.0.4

**Comment by GamerClassN7** [comment]
https://github.com/GamerClassN7/HA_Desktop_Companion/issues/85

**Comment by GamerClassN7** [comment]
As you cna read in related Issue this is intended behavour, and nothing can be done since API communication is handled by native API of HA same as IOS and Android apps. This change would need to be handeled on HA site, 

relate docs: [https://developers.home-assistant.io/docs/api/rest/](https://developers.home-assistant.io/docs/api/rest/) 

Closing Issue since it is out of scope :/

EDIT: there is workeround, you can check in automation and helper when last update ocured if it is > than update interval of sensor (in configuration.yaml) sensor is offline.
